# Generated by Django 5.0.1 on 2024-01-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/img/')),
                ('text', models.TextField(max_length=300)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
